title: CAD Github
description: >-
  To understand the standard Git concept, be familiar with SET Git workflows,
  and perform Git operations using CLI and GitHub UI.
template:
  repo: cad-github-template
  name: cad-github
before:
  - type: createIssue
    title: 'Step 1: Choose a JIRA Story'
    body: set-jira-story-id.md
    store:
      issue_url: '{{ result.data.html_url }}'
steps:
  - title: 'Step 1: Choose a JIRA Story'
    description: Choose a JIRA story to use in this course.
    event: issue_comment.created
    link: '{{ issue_url }}'
    actions:
      - type: gate
        operator: test
        right: '%payload.comment.body%'
        left: '[A-Z]+-\d+'
        else:
          - type: respond
            with: 'invalid-jira-story-id.md'
      - type: respond
        with: 'clone-repo.md'
  - title: 'Step 2: Clone the Repository'
    description: Clone this repository to your local computer.
    event: issue_comment.created
    link: {{ issue_url }}
    actions:
      - type: gate
        operator: ===
        right: done
        left: '%payload.comment.body%'
        store:
          jira_story_id: '%payload.comment.body%'
        else:
          - type: respond
            with: 'invalid-complete-response.md'
      - type: respond
        with: 'record-changes.md'
  - title: 'Step 3: Record Changes to the Repository'
    description: 'Understand the status of the current branch'
    event: issue_comment.created
    link: { { issue_url } }
      actions:
        - type: gate
          operator: ===
          right: done
          left: '%payload.comment.body%'
          else:
            - type: respond
              with: 'invalid-complete-response.md'
        - type: respond
          with: 'understand-branch-concept.md'
  - title: 'Step 4: Understand Git Branching'
    description: 'Understand the basic git branching concept'
    event: push
    link: { { issue_url } }
      actions:
        - type: gate
          operator: test
          left: '^{{ jira_story_id }}\s*: .+$'
          right: '%payload.head_commit.message%'
          else:
            - type: respond
              with: 'invalid-commit-message.md'
        - type: gate
          operator: ===
          left: '%payload.before%'
          right: 'c8bed0cf6ed3ac4ad5fc9a6fb3fca785be2e8cce'
          else:
            - type: respond
              with: 'invalid-branch-hierarchy.md'
