title: CAD Github
description: >-
  To understand the standard Git concept, be familiar with SET Git workflows,
  and perform Git operations using CLI and GitHub UI.
template:
  repo: cad-github-template
  name: cad-github
before:
  - type: createIssue
    title: 'Step 1: Choose a JIRA Story'
    body: set-jira-story-id.md
    store:
      step1_issue_url: '{{ result.data.html_url }}'
steps:
  - title: 'Step 1: Choose a JIRA Story'
    description: Choose a JIRA story to use in this course.
    event: issue_comment.created
    link: '{{ step1_issue_url }}'
    actions:
      - type: gate
        operator: test
        right: '%payload.comment.body%'
        left: '[A-Z]+-\d+'
        every: false
